version: '2.5'

services:
  api:
    image: converter
    container_name: converter_api
    build: .
    volumes:
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: postgres:15.2
    container_name: converter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - .:/app
    ports:
      - 5434:5432
    environment:
      DATABASE_NAME: ${NAME}
      DATABASE_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      DATABASE_HOST: localhost
      DATABASE_PORT: ${PORT}
volumes:
  postgres_data: